# Generated by Django 4.1.4 on 2023-09-22 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researcher', '0011_alter_researcher_position'),
        ('project', '0002_rename_date_project_start_date_project_end_date_and_more'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='img/news/')),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('mentioned', models.ManyToManyField(blank=True, related_name='news', to='researcher.researcher')),
                ('projects', models.ManyToManyField(blank=True, related_name='news', to='project.project')),
                ('related_news', models.ManyToManyField(blank=True, to='news.news')),
                ('research_lines', models.ManyToManyField(blank=True, related_name='news', to='research.research')),
            ],
        ),
    ]
