# Generated by Django 4.1.4 on 2022-12-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_sender', models.EmailField(max_length=200)),
                ('subject', models.TextField(max_length=300)),
                ('message', models.TextField()),
                ('to', models.ManyToManyField(related_name='messages', to='researcher.researcher')),
            ],
        ),
    ]
