# Generated by Django 4.1.4 on 2022-12-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('bio', models.TextField(default='')),
                ('mail', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('DIR', 'Director'), ('INV', 'Investigador'), ('PHD', 'Phd'), ('MG', 'Magister'), ('PG', 'Pregrado')], max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='photos/researchers/')),
                ('research_line', models.ManyToManyField(blank=True, related_name='researchers', to='research.research')),
            ],
        ),
    ]
