# Generated by Django 4.1.4 on 2023-01-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0002_alter_researcher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/img/researchers/'),
        ),
    ]
