# Generated by Django 4.1.4 on 2023-01-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0004_alter_researcher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='google_scholar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
