# Generated by Django 4.1.4 on 2023-01-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0005_researcher_github_researcher_google_scholar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='orcid',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='position',
            field=models.CharField(choices=[('DIR', 'Director'), ('INV', 'Investigador'), ('POST', 'Postdoc'), ('PHD', 'Phd'), ('MG', 'Magister'), ('PG', 'Pregrado')], max_length=100),
        ),
    ]
