# Generated by Django 4.1.4 on 2023-01-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0006_researcher_active_researcher_orcid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='position',
            field=models.CharField(choices=[('DIR', 'Director'), ('INV', 'Investigador'), ('TH', 'Tesista')], max_length=100),
        ),
    ]
