# Generated by Django 4.1.4 on 2023-08-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0007_alter_researcher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='position',
            field=models.CharField(choices=[('DIR', 'Director'), ('INV', 'Investigador'), ('TH_UG', 'Pregrado'), ('TH_UG', 'Magister'), ('TH_UG', 'Doctorado')], max_length=100),
        ),
    ]
