# Generated by Django 4.1.4 on 2023-09-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0008_alter_researcher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='position',
            field=models.CharField(choices=[('DIR', 'Director'), ('SUBDIR', 'Subdirector'), ('INV', 'Investigador principal'), ('COLAB', 'Investigador principal'), ('TH_UG', 'Alumno de Pregrado'), ('TH_UG', 'Alumno de Magister'), ('TH_UG', 'Alumno de Doctorado')], max_length=100),
        ),
    ]
