# Generated by Django 4.1.4 on 2023-10-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0011_alter_researcher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='position',
            field=models.CharField(choices=[('DIR', 'Director'), ('SUBDIR', 'Subdirector'), ('INV_P', 'Investigador principal'), ('INV_A', 'Investigador asociado'), ('INV_C', 'Investigador colaborador'), ('INV_E', 'Investigador extranjeros'), ('TH_UG', 'Alumno de Pregrado'), ('TH_PG', 'Alumno de Magister'), ('TH_PHD', 'Alumno de Doctorado')], max_length=100),
        ),
    ]
