# Generated by Django 4.1.4 on 2023-10-04 07:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0021_alter_researcher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[250, 280], upload_to='img/researchers/'),
        ),
    ]
