# Generated by Django 4.1.4 on 2023-09-27 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_alter_project_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('payed', models.BooleanField(default=False)),
                ('pay', models.IntegerField(blank=True, default=0)),
                ('offer_type', models.CharField(choices=[('PHD', 'Phd'), ('UG', 'Undergraduate'), ('MG', 'Master'), ('PPHD', 'Postdoc'), ('RA', 'Research Assistant'), ('R', 'Researcher')], max_length=100)),
                ('contact_mail', models.EmailField(max_length=200)),
                ('contact_phone', models.CharField(max_length=100)),
                ('offer_status', models.CharField(choices=[('O', 'open'), ('C', 'closed'), ('U', 'unpublished')], default='U', max_length=100)),
                ('project', models.ManyToManyField(blank=True, related_name='offers', to='project.project')),
            ],
        ),
    ]
