# Generated by Django 4.1.4 on 2023-09-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(choices=[('O', 'open'), ('C', 'closed'), ('U', 'unpublished')], default='U', max_length=100),
        ),
    ]
