# Generated by Django 4.1.4 on 2022-12-21 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('paper', '0001_initial'),
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField(default=datetime.date.today)),
                ('link', models.URLField(blank=True)),
                ('papers', models.ManyToManyField(blank=True, related_name='projects', to='paper.paper')),
                ('participants', models.ManyToManyField(blank=True, related_name='projects', to='researcher.researcher')),
                ('research_lines', models.ManyToManyField(blank=True, related_name='projects', to='research.research')),
            ],
        ),
    ]
