# Generated by Django 4.1.4 on 2023-09-22 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2028, 9, 22)),
        ),
        migrations.AddField(
            model_name='project',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
