# Generated by Django 4.1.4 on 2023-10-09 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0022_alter_researcher_photo'),
        ('project', '0006_alter_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='responsable_project', to='researcher.researcher'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2028, 10, 9)),
        ),
    ]
