# Generated by Django 4.1.4 on 2022-12-21 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('abstract', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('file', models.FileField(blank=True, upload_to='papers/')),
                ('link', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('JRN', 'Journal'), ('PRST', 'Presentation'), ('CON', 'Conference'), ('TH', 'Thesis')], max_length=100)),
                ('authors', models.ManyToManyField(blank=True, related_name='papers', to='researcher.researcher')),
                ('topic', models.ManyToManyField(blank=True, related_name='papers', to='research.research')),
            ],
        ),
    ]
