# Generated by Django 4.1.4 on 2023-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.CharField(choices=[('JRN', 'Journal'), ('PRST', 'Presentation'), ('CON', 'Conference'), ('TH', 'Thesis'), ('CH', 'Chapter')], max_length=100),
        ),
    ]
